---

#- name: Copiar Parametros
#  win_copy:
#    src: files/win-disable-ieesc.ps1
#    dest: 'c:\windows\temp\'


- name: Run powershell script to disable IE ESC for Administrators
  script: files/win-disable-ieesc.ps1

- name: Download Zabbix Agente 32bits para pasta TEMP
  win_get_url:
    url: "https://www.zabbix.com/downloads/{{zbx_win_agent_version}}/zabbix_agent-{{zbx_win_agent_version}}-windows-i386-openssl.msi"
    dest: 'c:\windows\temp\zabbix_agent.msi'
    force: true
    follow_redirects: all
  when: ansible_architecture == "32 bits"

- name: Download Zabbix Agente 64bits para pasta TEMP
  win_get_url:
    url: "https://www.zabbix.com/downloads/{{zbx_win_agent_version}}/zabbix_agent-{{zbx_win_agent_version}}-windows-amd64-openssl.msi"
    dest: 'c:\windows\temp\zabbix_agent.msi'
    force: true
    follow_redirects: all

- name: Instalacao do Zabbix Agente
  win_package:
    path: c:\windows\temp\zabbix_agent.msi
    arguments: /qn SERVER=127.0.0.1 INSTALLFOLDER="C:\Program Files\Zabbix Agent\" 
  notify: Stop Win Zabbix Agent

- name: Copiando arquivos de configuracao
  win_template:
    src: zabbix_agentd_5.conf
    dest: '{{ zbx_win_folder_conf }}\zabbix_agentd.conf'
  when: zbx_win_agent_versionconf >= 5

- name: Copiando arquivos de configuracao
  win_template:
    src: zabbix_agentd_4.conf
    dest: '{{ zbx_win_folder_conf }}\zabbix_agentd.conf'
  when: zbx_win_agent_versionconf <= 4

- name: Criar pasta
  win_file:
    path: "{{ zbx_agent_win_Scritps }}"
    state: directory

- name: Copiar scripts PS1 para pasta
  win_copy:
    src: files/scripts
    dest: '{{ zbx_win_folder_conf }}'

- name: Copiar Parametros
  win_copy:
    src: files/zabbix_agentd.conf.d
    dest: '{{ zbx_win_folder_conf }}'

- name: Configurar restart do servico zabbix agent
  win_shell: sc.exe failure "Zabbix Agent" actions= restart/5000/restart/10000/restart/20000 reset= 86400

- name: Configurando Firewall do Windows
  win_firewall_rule:
    name: Allow Zabbix Agentd
    localport: 10050-10051
    action: allow
    direction: in
    protocol: tcp
    state: present
    enable: yes
  notify: Start Win Zabbix Agent

- name: Iniciar o serviço do Zabbix Agent
  win_service:
    name: "{{ item }}"
    state: started
  loop:
    - "{{ zbx_win_agent_service  }}"
...
